require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAnalyticsWithoutAdIdSupport=true

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'AdoreBeauty' do
  config = use_native_modules!

  #//TODO rn68 investigate how local env flags work
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,# flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # fixed pods that dont auto-link
  pod 'ForterSDK', :git => 'https://forter-mobile-git:zvGKcVtDhkfj4asNekSn@bitbucket.org/forter-mobile/forter-ios-sdk.git'
  pod 'BraintreeDropIn', :inhibit_warnings => true
  pod "tealium-react-native-swift", :path => '../node_modules/tealium-react-native/tealium-react-native-swift.podspec'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({'Flipper' => '0.137.0'})

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # apply changes to ios/Pods/Pods.xcodeproj/project.pbxproj
    installer.pods_project.build_configurations.each do |config|
      if config.name == "Debug"
        # exclude pods from arm64 build
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
      end
    end
  end
end

target "EmarsysAppNotificationService" do
  pod 'EmarsysNotificationService'
end
